username: '153909*****'
password: '********'
heartbeatPacket: true
routerMode: true
autoFetchIP: true
#clientIP:
#nasIP:
#mac:
debugMode: false
useLog4j: true
useJLine: true
useSpecifiedDNS: true
specifiedDNS: '202.96.128.166,202.96.134.133'