username: null
password: null
heartbeatPacket: true
autoFetchIP: true
clientIP: null
nasIP: null
mac: null
debugMode: false
useLog4j: true
useJLine: true
useSpecifiedDNS: true
specifiedDNS: '202.96.128.166,202.96.134.133'